export var italianWords: string[] = [
  "Ciao",
  "Buonasera",
  "Buonanotte",
  "Buongiorno",
  "Grazie mille",
  "Piacere di conoscerti",
  "Non capisco",
  // "Parla Inglese?",
  // "Settimana",
  // "Anno",
  // "Oggi",
  // "Domani",
  // "Ieri",
  // "Piccolo",
  // "Buono",
  // "Difficile",
  // "Facile",
  // "Cattivo",
  // "Come stai?",
  // "Arrivederci",
  // "Caffé",
  // "Birra",
  // "Té",
  // "Vino",
  // "Acqua",
  // "Manzo",
  // "Maiale",
  // "Pollo",
  // "Pesce",
  // "Piede",
  // "Gamba",
  // "Testa",
  // "Braccio",
  // "Mano",
  // "Dito",
  // "Corpo",
  // "Stomaco",
  // "Schiena",
  // "Petto",
  // "Infermiere",
  // "Impiegato",
  // "Cuoco",
  // "Ingegnere",
  // "Dottore",
  // "Dirigente",
  // "Insegnante",
  // "Programmatore",
  // "Venditore",
  // "Calendario",
  // "Orologio",
];

export var englishWords: string[] = [
  "hello",
  "good evening",
  "good night",
  "good morning",
  "thank you very much",
  "nice to meet you",
  `i don't understand`,
  // "do you speak english?",
  // "week",
  // "year",
  // "today",
  // "tomorrow",
  // "yesterday",
  // "small",
  // "good",
  // "difficult",
  // "easy",
  // "bad",
  // "how are you?",
  // "goodbye",
  // "coffee",
  // "beer",
  // "tea",
  // "wine",
  // "water",
  // "beef",
  // "pork",
  // "chicken",
  // "fish",
  // "foot",
  // "leg",
  // "head",
  // "arm",
  // "hand",
  // "finger",
  // "body",
  // "stomach",
  // "back",
  // "chest",
  // "nurse",
  // "employee",
  // "cook",
  // "engineer",
  // "doctor",
  // "manager",
  // "teacher",
  // "programmer",
  // "salesman",
  // "calendar",
  // "clock",
];
